DROP TABLE IF EXISTS invite;
DROP TABLE IF EXISTS include;
DROP TABLE IF EXISTS trip;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS guide;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS destination;
DROP TABLE IF EXISTS hotel;
